#!/bin/expect -f
# test plotcake keyboard event handle
set timeout 4
set init_rows [stty rows]
set init_cols [stty columns]

# If the window is too small, the expected output information will be covered
# by other information. Therefore, we need to set a window size that is large
# enough to display the expected information.
set stty_init "rows 64 cols 132"

log_file -noappend examples.exp.log

set title "TITLE_XYZ"
set xlabel "AXIS_X"
set ylabel "AXIS_Y"
set line0 "LINE_0"
set line1 "LINE_1"

spawn bash -c "while sleep 0.01; do echo 1 2; done |
	./plotcake --title $title --xlabel $xlabel --ylabel $ylabel \
		-l $line0 -l $line1 --verbose"
sleep 0.1

proc test_init {pattern} {
	global timeout
	expect {
		"$pattern" {}
		timeout {
			send_user "FATAL: not found pattern '$pattern'\n"
			exit 1
		}
	}
}

proc test_key {key pattern} {
	global timeout
	send "$key"
	expect {
		"$pattern" {}
		timeout {
			send_user "Fatal: key '$key' failed, expect '$pattern'\n"
			exit 1
		}
	}
	# Allow UI to refresh
	sleep 0.05
}

# Verify initial plot
test_init "$title"
# test_init "$ylabel"
test_init "$line0"
test_init "plot(redraw="
test_init "key(left="
test_init "enter="
test_init "github.com/rtoax/plotcake"

# Verify keys
test_key "l" " $line0"
test_key "l" " $line1"
test_key "h" "'q': quit"
test_key "r" "cur=114="
test_key "t" "(signed logarithmic)"
test_key "t" "(base-10 signed logarithmic)"
test_key "t" "(base-e exponential)"
test_key "t" "(delta)"
# First enter
test_key "\r" "1 "
# Another enter
test_key "\r" "cur=13="

test_key "\033" "cur=27="

test_key "\033\[B" "cur=258="
test_key "\033\[B" "KEY_DOWN"

test_key "\033\[A" "cur=259="
test_key "\033\[A" "KEY_UP"

test_key "\033\[D" "cur=260="
test_key "\033\[D" "KEY_LEFT"

test_key "\033\[C" "cur=261="
test_key "\033\[C" "KEY_RIGHT"

send "q"
expect eof
set stty_init "rows $init_rows cols $init_cols"

spawn bash -c "reset || :"
spawn bash -c "resize || :"
puts "PASS"
